config/routes.rb
OptimacmsBackups::Engine.routes.draw do
#Rails.application.routes.draw do
  scope '/'+Optimacms.config.admin_namespace do
    scope module: 'admin', as: 'admin' do
      # options
      resources :backups do
        collection do
          get 'perform'
          get 'download'
          get 'delete'
        end
      end
    end
  end
end

app/controllers/optimacms_backups/admin/backups_controller.rb
class  OptimacmsBackups::Admin::BackupsController < Optimacms::Admin::AdminBaseController

  def index

    @list_backups = {
        'db'=>init_list('db_backup'),
        'app_files'=>init_list('app_files_backup'),
        'user_files'=>init_list('user_files_backup'),
    }
  end

  def init_list(t)
    res = []

    #
    files = []

    Dir["#{dir_backups}#{t}/**/*.tar"].each do |f|
      files << f
    end

    files = files.sort_by{ |x| File.mtime(x) }.reverse

    res = files.map do |f|
      r = {}
      r[:shortpath] = f.gsub /#{dir_backups}/, ''
      r[:path] = f
      r[:size] = File.size(f)

      r
    end


    res
  end


  def perform
    t = params[:t] || 'full'

    if t=='full'
      @res = perform_backup_full
    else
      @res = perform_backup(t)
    end



    respond_to do |format|
      format.html {      }
      format.json{        render :json=>@res      }
    end
  end


  def download
    f = params[:f]

    path = File.join(dir_backups, f)

    send_data File.read(path), filename: f
  end

  def delete
    f =  CGI::unescape(params[:f])
    @res = delete_backup(f)

    if @res[:res]==0
      raise 'Error deleting file'
    end

    #
    respond_to do |format|
      format.html {      }
      format.js{ }
      format.json{        render :json=>@res      }
    end
  end


  private





  def perform_backup_full
    res1 = perform_backup('db')
    res2 = perform_backup('app_files')
    res3 = perform_backup('user_files')


    {res: (res1[:res]==1 && res2[:res]==1 && res3[:res]==1 ? 1 : 0), output: ""}
  end

  def perform_backup(t)
    cmd = %Q(app_env=#{Rails.env} RAILS_ENV=#{Rails.env} bundle exec backup perform -t #{t}_backup --root-path backup 2>&1)

    output = ''

    Bundler.with_clean_env do
      output = `#{cmd}`
    end


    {res: 1, output: output}
  end


  def delete_backup(f)
    path = File.join(dir_backups, f)

    File.delete(path)

    return {res:1 , output: "deleted"}
  rescue Exception => e
    return {res: 0, output: "error"}
  end


  def dir_backups
    OptimacmsBackups.backups_config['dir_backups_base']

  end

end

app/helpers/optimacms_options/application_helper.rb
module OptimacmsBackups
  module ApplicationHelper
  end
end

app/helpers/optimacms_options/filter_helper.rb
module OptimacmsBackups
  module FilterHelper
    def self.for_select_yes_no_visible_client
      a = [["all visible client", -1], ["yes", 1], ["no", 0]]
      a
    end

    def self.for_select_yes_no_need_notify
      a = [["all need notify", -1], ["yes", 1], ["no", 0]]
      a
    end


  end
end

app/views/layouts/optimacms_backups/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OptimacmsBackups</title>
  <%= stylesheet_link_tag    "optimacms_backups/application", media: "all" %>
  <%= javascript_include_tag "optimacms_backups/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/optimacms_backups/admin/backups/_list.html.haml
%h2 Backups - Local
Local storage at #{OptimacmsBackups.backups_config['dir_backups_base']}
%br
click to download

- @list_backups.each do |name, list|
  %h3=name
  %ul.list-backups
    - list.each do |r|
      %li{data: {f: r[:shortpath]}}
        =link_to r[:shortpath], download_admin_backups_path(f: r[:shortpath]), target: '_blank'
        (
        #{number_to_human_size(r[:size])}
        )
        (
        =link_to 'delete', delete_admin_backups_path(f: Rack::Utils.escape(r[:shortpath])), :confirm => "Are you sure?", :method => :get, remote: true, :class=>'link_delete'
        )
        %br


%h2 Backups config

Storages:
%ul
  - OptimacmsBackups.backups_config['storages'].each do |r|
    %li
      =r['type']

app/views/optimacms_backups/admin/backups/index.html.haml
.page-header
  .row
    .col-md-7
      %h1
        Backups
        %small
          <i class="ace-icon fa fa-angle-double-right"></i>
          manage backups

%h2 Commands

%ul.list-inline#commands
  %li=link_to 'Backup all', '#', :class=>'btn btn-primary btn-sm', :"data-name"=>'command', :"data-cmd"=>'perform', :"data-cmd-type"=>"full"
  %li=link_to 'Backup app files', '#', :class=>'btn btn-primary btn-sm', :"data-name"=>'command', :"data-cmd"=>'perform', :"data-cmd-type"=>"app_files"
  %li=link_to 'Backup user files', '#', :class=>'btn btn-primary btn-sm', :"data-name"=>'command', :"data-cmd"=>'perform', :"data-cmd-type"=>"user_files"
  %li=link_to 'Backup DB', '#', :class=>'btn btn-primary btn-sm', :"data-name"=>'command', :"data-cmd"=>'perform', :"data-cmd-type"=>"db"

#status_commands.bg-info.well

= render 'list'

:javascript
  // commands
  $( '#commands a[data-name="command"]' ).click(function() {
    //$('#status_commands').html("Handler for .click() called." );
    send_command($(this).data('cmd'), $(this).data('cmd-type'));
  });

  function send_command(cmd, t){
    $('#status_commands').html("Sending...");

    $.ajax({
      url: "/#{Optimacms.config.admin_namespace}/backups/" + cmd,
      data: {t: t},
      type: "GET",
      dataType: "json",
      contentType: "application/json",
      beforeSend: function(){
        // Handle the beforeSend event
      },
      success: function(res){
        $('#status_commands').html("Result: "+res.res+", output: "+res.output);
      },

      complete: function (res) {

      }

    });
  }


  // delete
  $("ul.list-backups").on( "ajax:success", "li a.link_delete", function() {
    $(this).closest('li').hide();
  });